package core.common.exceptions

class AuthException : Exception() {}